.PHONY: clean All

All:
	@echo "----------Building project:[ NormalPractice - Debug ]----------"
	@cd "NormalPractice" && "$(MAKE)" -f  "NormalPractice.mk"
clean:
	@echo "----------Cleaning project:[ NormalPractice - Debug ]----------"
	@cd "NormalPractice" && "$(MAKE)" -f  "NormalPractice.mk" clean
