.PHONY: clean All

All:
	@echo "----------Building project:[ GreedyAlgorithm - Debug ]----------"
	@cd "GreedyAlgorithm" && "$(MAKE)" -f  "GreedyAlgorithm.mk"
clean:
	@echo "----------Cleaning project:[ GreedyAlgorithm - Debug ]----------"
	@cd "GreedyAlgorithm" && "$(MAKE)" -f  "GreedyAlgorithm.mk" clean
