.PHONY: clean All

All:
	@echo "----------Building project:[ ArrayPractice - Debug ]----------"
	@cd "CodePractice" && "$(MAKE)" -f  "ArrayPractice.mk"
clean:
	@echo "----------Cleaning project:[ ArrayPractice - Debug ]----------"
	@cd "CodePractice" && "$(MAKE)" -f  "ArrayPractice.mk" clean
